# Generated by Django 3.2.6 on 2021-09-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NID_Number', models.IntegerField()),
                ('Birth_Date', models.DateField()),
                ('Phone', models.IntegerField()),
                ('Service', models.CharField(max_length=30)),
                ('Extra_Info', models.CharField(blank=True, max_length=30)),
                ('Status', models.BooleanField(default=False)),
                ('Certificate_Img', models.ImageField(blank=True, upload_to='pics')),
                ('Certificate_Status', models.BooleanField(default=False)),
                ('VaccineCard_Img', models.ImageField(blank=True, upload_to='pics2')),
                ('VaccineCard_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
